IHA/IHA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
# Django Password Reset için kullanılır
from django.contrib.auth import views as auth_views 
urlpatterns = [
    # Django dil secenekleri için /tr/ veya /en/ gibi bir url ekler
    path('i18n/', include('django.conf.urls.i18n')),
    # Admin paneli için
    path('admin/', admin.site.urls),
    # Api urls
    path('api/', include("iha_api.api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    
    # Pass Reset
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='pass_reset/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pass_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pass_reset/password_reset_complete.html'), name='password_reset_complete'),
    
    # My apps urls
    path('user/', include('user_app.urls')),
    path('', include('iha_app.urls')),
]

IHA/user_app/urls.py
from django.urls import path
from .views import *

app_name = 'user_app' 
urlpatterns = [
    path('login/', login_, name='login_'),
    path('logout/', logout_, name='logout'),
    path('register/', register, name='register'),
]

IHA/templates/register/register.html
<!doctype html>
<html lang="en">
  {% load static %}
  {% load crispy_forms_tags %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Login Page</title>
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    
  </head>

  <body class="">
    <div class="container">
      <div class = "row justify-content-center">
        <div class="col-8">
          {% include  'base/message.html' %}
          <form class="form-signin", method="post">
            <div class="text-center">
                <img class="mb-4 text-center" src="{% static 'img/logo/baykar.png' %}" alt="" width="128" height="96">
            </div>
            <h1 class="h3 mb-3 font-weight-normal">Hesap Oluşturun</h1>
            {% csrf_token %}
            {{form|crispy}}
            <div class="mb-2 d-flex justify-content-between">
              <button class="btn btn-sm btn-success btn-block" type="submit">Kaydet</button>
              <a href="{% url 'user_app:login_' %}" class="text-sm text-dark text-decoration-none ">Giriş Yap</a>
            </div>
              <div class="text-center font-weight-bold">
              <p class="mt-5 mb-3 text-muted">&copy; 2021-2022</p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>