IHA/IHA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
# Django Password Reset için kullanılır
from django.contrib.auth import views as auth_views 
urlpatterns = [
    # Django dil secenekleri için /tr/ veya /en/ gibi bir url ekler
    path('i18n/', include('django.conf.urls.i18n')),
    # Admin paneli için
    path('admin/', admin.site.urls),
    # Api urls
    path('api/', include("iha_api.api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    
    # Pass Reset
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='pass_reset/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pass_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pass_reset/password_reset_complete.html'), name='password_reset_complete'),
    
    # My apps urls
    path('user/', include('user_app.urls')),
    path('', include('iha_app.urls')),
]

IHA/iha_app/urls.py
from django.urls import path
from .views import *

app_name = 'IHA'
urlpatterns = [
    path('', index, name='index'),
    path('iha-list/', iha_list, name='iha_list'),
    path('iha-create/', add_new_iha, name='add_new_iha'),
    path('iha-update/<int:id>', update_iha, name='update_iha'),
    path('iha-delete/<int:id>', delete_iha, name='delete_iha'),
    path('add-new-category/', add_new_category, name='add_new_category'),

]

IHA/user_app/urls.py
from django.urls import path
from .views import *

app_name = 'user_app' 
urlpatterns = [
    path('login/', login_, name='login_'),
    path('logout/', logout_, name='logout'),
    path('register/', register, name='register'),
]

IHA/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Home Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="assets/images/favicon.ico">
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="light-style" />
        <link href="{% static 'assets/css/app-dark.min.css' %}" rel="stylesheet" type="text/css" id="dark-style" />
    </head>
    <body class="loading" data-layout-config='{"leftSideBarTheme":"light","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false}'>
        
        <div class="wrapper">
          {% include 'base/leftside.html' %}
            <div class="content-page">
              
                <div class="content">
                  {% include 'base/navbar.html' %}
                    <div class="container-fluid">
                        <div class="row">
                            {% include 'base/message.html' %}
                            <div class="col-12">
                                <div class="page-title-box">
                                    {% block body%}
                                    {% endblock %}
                                </div>
                            </div>
                        </div>     
                    </div> 
                </div> 
            </div>
        </div>
        {% include 'base/footer.html' %}
        <script src="{% static 'assets/js/vendor.min.js' %}"></script>
        <script src="{% static 'assets/js/app.min.js' %}"></script>
        
    </body>
</html>

IHA/templates/base/footer.html
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © 2022 - OktaySakarya
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

IHA/templates/base/leftside.html
{% load static %}
<div class="leftside-menu">
    <a href="{% url 'IHA:index' %}" class="logo text-center logo-light">
        <span class="logo-lg">
            <img src="{% static 'img/logo/baykar.png' %}" alt="" height="96">
        </span>
        <span class="logo-sm">
            <img src="{% static 'img/logo/BaykarLogo.png' %}" alt="" height="48">
        </span>
    </a>
    <a href="{% url 'IHA:index' %}" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="{% static 'img/logo/baykar.png' %}" alt="" height="96">
        </span>
        <span class="logo-sm">
            <img src="{% static 'img/logo/BaykarLogo.png' %}" alt="" height="48">
        </span>
    </a>

    <div class="h-100" id="leftside-menu-container" data-simplebar>
        <ul class="side-nav">
            <li class="side-nav-title side-nav-item">Dashboard</li>

            <li class="side-nav-item">
                <a href="{% url 'IHA:index' %}" class="side-nav-link">
                    <i class="uil-calender"></i>
                    <span> Kategoriler </span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="{% url 'IHA:add_new_category' %}" class="side-nav-link">
                    <i class="uil-calender"></i>
                    <span> Yeni Kategori Ekle </span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="{% url 'IHA:add_new_iha' %}" class="side-nav-link">
                    <i class="mdi mdi-import"></i>
                    <span> İha Ekle </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="{% url 'IHA:iha_list' %}" class="side-nav-link">
                    <i class="mdi mdi-format-list-bulleted"></i>
                    <span> İha Listele </span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="../../api/" class="side-nav-link">
                    <i class="mdi mdi-api"></i>
                    <span> İha API </span>
                </a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>

IHA/templates/base/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show mt-2" role="alert">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}                   
{% endif %}

IHA/templates/base/navbar.html
{% load static %}
<div class="navbar-custom">
  <ul class="list-unstyled topbar-menu float-end mb-0">
      <li class="dropdown notification-list">
          <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false"
              aria-expanded="false">
              <span class="account-user-avatar"> 
                  <img src="{% static 'assets/images/users/avatar-1.png' %}" alt="user-image" class="rounded-circle">
              </span>
              <span>
                  <span class="account-user-name">{{request.user.first_name}}</span>
                  <span class="account-position">{{request.user.last_name}}</span>
              </span>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
              <div class=" dropdown-header noti-title">
                  <h6 class="text-overflow m-0">HoşGeldin !</h6>
              </div>
              <a href="javascript:void(0);" class="dropdown-item notify-item">
                  <i class="mdi mdi-account-circle me-1"></i>
                  <span>Hesabım</span>
              </a>
              <a href="{% url 'user_app:logout' %}" class="dropdown-item notify-item">
                  <i class="mdi mdi-logout me-1"></i>
                  <span>Çıkış Yap</span>
              </a>
          </div>
      </li>
  </ul>
  <button class="button-menu-mobile open-left">
      <i class="mdi mdi-menu"></i>
  </button>
  <div class="app-search dropdown d-none d-lg-block">
    <form method="get">
        <div class="input-group">
            <input type="search" class="form-control dropdown-toggle" name="q" value="{{ request.GET.q }}" placeholder="Ara..." id="top-search">
            <span class="mdi mdi-magnify search-icon"></span>
            <button class="input-group-text btn-primary" type="submit">Ara</button>
        </div>
    </form>
  </div>
</div>