IHA/IHA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
# Django Password Reset için kullanılır
from django.contrib.auth import views as auth_views 
urlpatterns = [
    # Django dil secenekleri için /tr/ veya /en/ gibi bir url ekler
    path('i18n/', include('django.conf.urls.i18n')),
    # Admin paneli için
    path('admin/', admin.site.urls),
    # Api urls
    path('api/', include("iha_api.api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    
    # Pass Reset
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='pass_reset/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pass_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pass_reset/password_reset_complete.html'), name='password_reset_complete'),
    
    # My apps urls
    path('user/', include('user_app.urls')),
    path('', include('iha_app.urls')),
]

IHA/iha_app/urls.py
from django.urls import path
from .views import *

app_name = 'IHA'
urlpatterns = [
    path('', index, name='index'),
    path('iha-list/', iha_list, name='iha_list'),
    path('iha-create/', add_new_iha, name='add_new_iha'),
    path('iha-update/<int:id>', update_iha, name='update_iha'),
    path('iha-delete/<int:id>', delete_iha, name='delete_iha'),
    path('add-new-category/', add_new_category, name='add_new_category'),

]

IHA/iha_app/models.py
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.safestring import mark_safe
from django.utils.text import slugify
# Create your models here.
class Category(MPTTModel):
    STATUS = (
        ('True', 'Aktif'),
        ('False','Pasif'),
    )
    parent = TreeForeignKey('self',blank=True, null=True ,related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    image=models.ImageField(blank=True,upload_to='images/')
    status=models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):                           
        full_path = [self.title]           
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])
    
    def save(self, *args, **kwargs):
        self.slug = self.get_uniqe_slug()
        return super(Category, self).save(*args, **kwargs)

    def get_uniqe_slug(self):
        slug = slugify(self.title + "-" + self.keywords).replace("ı", "i")
        uniqe_slug = slug
        counter = 1
        while Category.objects.filter(slug=uniqe_slug).exists():
            uniqe_slug = "{}-{}".format(slug, counter)
            counter += 1
        return uniqe_slug

class IHA(models.Model):
    STATE=(
        ('Available','Müsait'),
        ('Unavailable','Kullanım Dışı'),
        ('Faulted','Hatalı')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category_iha") #many to one relation with Category
    device_serial_number = models.CharField(max_length=50, unique=True)
    device_id = models.CharField(max_length=50, unique=True)
    device_name = models.CharField(max_length=50)
    device_type = models.CharField(max_length=50)
    device_status = models.CharField(
                    default='Available',
                    max_length=50,
                    choices=STATE,
                    verbose_name='Durum',
                    null=True,
                    blank=True
                    )
    device_image = models.ImageField("Cihazın Resmini Yükleyin",upload_to='images/iha', blank=True, null=True)
    device_weight = models.FloatField(
        default=0,
        validators=[MinValueValidator(0.0), MaxValueValidator(99999.0)],
    )
    device_ammo_capacity = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9999)],
        default=0
    )
    device_ammo_level = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=0
    )
    device_fuel_capacity = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9999)],
        default=0
    )
    device_fuel_level = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=0
    )
    # Battery pack capacity
    device_battery_capacity = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9999)],
        default=0
    )
    # Battery pack level
    device_battery_level = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=0
    )
    # iha flying range
    device_flying_range = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(99999.0)],
        default=0
    )
    # iha flying speed
    device_flying_speed = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(99999.0)],
        default=0
    )
    # iha flying altitude
    device_flying_altitude = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(99999.0)],
        default=0
    )
    created_iha = models.DateTimeField("Eklenme Tarihi",auto_now_add= True,blank=True)

    def __str__(self):
        return f"IHA: {self.device_id} {self.device_name} {self.device_type}"    
    def image_tag(self):
        if self.device_image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.device_image.url))
        else:
            return ""
    class Meta:
        verbose_name_plural = 'IHA'
        ordering = ['-created_iha']

class Images(models.Model):
    product=models.ForeignKey(IHA,on_delete=models.CASCADE, related_name="images")
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/iha')
    def __str__(self):
        return self.title
    

IHA/templates/iha/add_category.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row justify-content-center mt-4">
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Kategori Ekle</h6>
            </div>
            <div class="card-body">
              <form class="user" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary btn-user btn-block mt-2" value="Kaydet">
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

IHA/templates/iha/add_new_iha.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row justify-content-center mt-4">
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Yeni IHA Ekle</h6>
            </div>
            <div class="card-body">
              <form class="user" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary btn-user btn-block mt-2" value="Kaydet">
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

IHA/templates/iha/iha_list.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% block body%}
<h4>IHA LIST</h4>
<div class="row justify-content-center mt-4">
    <div class="col-xl-10 col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark text-center">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Resim</th>
                        <th class="text-center">IHA Adı</th>
                        <th class="text-center">Iha id</th>
                        <th>İha Sınıfı</th>
                        <th>İha Status</th>
                        <th>Mühümmat Kapasitesi</th>
                        <th class="text-center">İha Ağırlık</th>
                        <th class="text-center">Uçuş Menzili</th>
                        <th class="text-center">Eylemler</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for iha in iha_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>
                                {% if iha.device_image %}
                                    <img src="{% static iha.device_image.url %}" width="50" alt="iha image">
                                {% else %}
                                    Eklenmemiş
                                {% endif %} 
                            </td>
                            <td class="text-decoration-none font-weight-bold text-dark text-center">
                                {{iha.device_name}}
                            </td>
                            <td class="text-decoration-none font-weight-bold text-dark">
                                {{iha.device_id}}
                            </td>
                            <td class="text-dark text-decoration-none text-success font-weight-bold">
                                <i class="mdi mdi-id-card text-dark font-weight-bold"></i>
                                {{ iha.device_type }}
                            </td>
                            <td class="text-dark font-weight-bold text-decoration-none">
                                {{ iha.get_device_status_display }}
                            </td>
                            <td class="text-dark text-decoration-none text-success text-center">
                                <i class="mdi mdi-rocket"></i>
                                {{ iha.device_ammo_capacity }}
                            </td>
                            <td class="text-dark text-decoration-none text-success text-center">
                                <i class="mdi mdi-weight"></i>
                               {{ iha.device_weight }}
                            </td>
                            <td class="text-decoration-none font-weight-bold text-center text-dark">
                                <i class="mdi mdi-airplane-takeoff"></i>
                                {{ iha.device_flying_range }}
                            </td>
                            <td class="text-center">
                                <a class="text-decoration-none" href="{% url 'IHA:update_iha' iha.id %}">
                                    <i class="mdi mdi-book-edit text-warning" style="font-size: 24px;"></i>
                                </a>
                                <a class="text-decoration-none" href ={% url 'IHA:delete_iha' iha.id %} >
                                    <i class="mdi mdi-trash-can-outline text-danger" style="font-size: 24px;"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row mb-4">
            <div class="col">
                <span class="text-xs text-dark-800 text-left">
                    {% trans 'Toplam' %} {{paginator.count}} {% trans 'iha mevcut' %} {{iha_list.start_index}}-{{ iha_list.end_index }} {% trans 'gösteriliyor' %}
                </span>
            </div>
            <div class="col-auto">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                    {% if iha_list.has_previous %}
                        <li class="page-item">
                        <a class="page-link" href="?p={{ iha_list.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            
                        </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                
                            </a>
                        </li>
                        {% endif %}
                        {% for i in page_range %}
                            {% if i == iha_list.number %}
                                <li class="page-item active"><a class="page-link" href="?p={{i}}">{{i}}</a></li>
                            {% else %}
                                {% if i == page_obj.paginator.ELLIPSIS %}
                                    <li class="page-item"><span class="page-link">{{i}}</span></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?p={{i}}">{{i}}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if iha_list.has_next %}
                        <li class="page-item">
                                <a class="page-link" href="?p={{ iha_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>  
{% endblock %}

IHA/templates/iha/update_iha.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row justify-content-center mt-4">
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Yeni IHA Ekle</h6>
            </div>
            <div class="card-body">
              <form class="user" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary btn-user btn-block mt-2" value="Güncelle">
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}